=== fraliphsoft/dataAgr/Data/xml&xsd/result_xs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="api">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="source"/>
        <xs:element ref="methods"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="source" type="xs:anyURI"/>
  <xs:element name="methods">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="method"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="method">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="class"/>
        <xs:element ref="name"/>
        <xs:element ref="signature"/>
        <xs:element ref="desc"/>
        <xs:element ref="parameters"/>
        <xs:element ref="return"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="class" type="xs:NCName"/>
  <xs:element name="signature" type="xs:string"/>
  <xs:element name="parameters">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="param"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="param">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="type"/>
        <xs:element ref="desc"/>
        <xs:element minOccurs="0" ref="default"/>
        <xs:element ref="optional"/>
        <xs:element ref="options"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="optional" type="xs:boolean"/>
  <xs:element name="options">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="option"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="option">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="type"/>
        <xs:element minOccurs="0" ref="default"/>
        <xs:element ref="desc"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="return">
    <xs:complexType>
      <xs:sequence minOccurs="0">
        <xs:element ref="type"/>
        <xs:element ref="desc"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="desc" type="xs:string"/>
  <xs:element name="type" type="xs:string"/>
  <xs:element name="default" type="xs:string"/>
</xs:schema>

=== fraliphsoft/dataAgr/API_Stack/src/main/java/com/edu/nju/data/result_mongodb.xml
<?xml version="1.0" encoding="UTF-8"?>
<api xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="result_xs.xsd">
  <name>mongodb nodejs driver</name>
  <source>http://mongodb.github.io/node-mongodb-native/3.0/api/index.html</source>
  <methods>
    <method>
      <name>addUser</name>
      <parameters>
        <param>
          <optional>false</optional>
          <options/>
          <type>string</type>
          <name>username</name>
          <desc>The username.</desc>
        </param>
        <param>
          <optional>false</optional>
          <options/>
          <type>string</type>
          <name>password</name>
          <desc>The password.</desc>
        </param>
        <param>
          <optional>true</optional>
          <options>
            <option>
              <default>null</default>
              <type>number
|

string</type>
              <name>w</name>
              <desc>The write concern.</desc>
            </option>
            <option>
              <default>null</default>
              <type>number</type>
              <name>wtimeout</name>
              <desc>The write concern timeout.</desc>
            </option>
            <option>
              <default>false</default>
              <type>boolean</type>
              <name>j</name>
              <desc>Specify a journal write concern.</desc>
            </option>
            <option>
              <default>false</default>
              <type>boolean</type>
              <name>fsync</name>
              <desc>Specify a file sync write concern.</desc>
            </option>
            <option>
              <default>null</default>
              <type>object</type>
              <name>customData</name>
              <desc>Custom data associated with the user (only Mongodb 2.6 or higher)</desc>
            </option>
            <option>
              <default>null</default>
              <type>Array.&lt;object&gt;</type>
              <name>roles</name>
              <desc>Roles associated with the created user (only Mongodb 2.6 or higher)</desc>
            </option>
            <option>
              <default/>
              <type>ClientSession</type>
              <name>session</name>
              <desc>optional session to use for this operation</desc>
            </option>
          </options>
          <type>object</type>
          <name>options</name>
          <desc>Optional settings</desc>
        </param>
        <param>
          <optional>false</optional>
          <options/>
          <type>Admin~resultCallback</type>
          <name>callback</name>
          <desc>optional
The command result callback</desc>
        </param>
      </parameters>
      <return>
        <type>Promise</type>
        <desc>Promise if no callback passed</desc>
      </return>
      <signature>addUser(username, password, options, callback)</signature>
      <class>Admin</class>
      <desc>Add a user to the database.</desc>
    </method>
    <method>
      <name>buildInfo</name>
      <parameters>
        <param>
          <optional>true</optional>
          <options>
            <option>
              <default/>
              <type>ClientSession</type>
              <name>session</name>
              <desc>optional session to use for this operation</desc>
            </option>
          </options>
          <type>Object</type>
          <name>options</name>
          <desc>Optional settings</desc>
        </param>
        <param>
          <optional>false</optional>
          <options/>
          <type>Admin~resultCallback</type>
          <name>callback</name>
          <desc>optional
The command result callback</desc>
        </param>
      </parameters>
      <return>
        <type>Promise</type>
        <desc>Promise if no callback passed</desc>
      </return>
      <signature>buildInfo(options, callback)</signature>
      <class>Admin</class>
      <desc>Retrieve the server information for the currentinstance of the db client</desc>
    </method>
    <method>
      <name>command</name>
      <parameters>
        <param>
          <optional>false</optional>
          <options/>
          <type>object</type>
          <name>command</name>
          <desc>The command hash</desc>
        </param>
        <param>
          <optional>true</optional>
          <options>
            <option>
              <default>null</default>
              <type>ReadPreference
|

string</type>
              <name>readPreference</name>
              <desc>The preferred read preference (ReadPreference.PRIMARY, ReadPreference.PRIMARY_PREFERRED, ReadPreference.SECONDARY, ReadPreference.SECONDARY_PREFERRED, ReadPreference.NEAREST).</desc>
            </option>
            <option>
              <default>null</default>
              <type>number</type>
              <name>maxTimeMS</name>
              <desc>Number of milliseconds to wait before aborting the query.</desc>
            </option>
          </options>
          <type>object</type>
          <name>options</name>
          <desc>Optional settings</desc>
        </param>
        <param>
          <optional>false</optional>
          <options/>
          <type>Admin~resultCallback</type>
          <name>callback</name>
          <desc>optional
The command result callback</desc>
        </param>
      </parameters>
      <return>
        <type>Promise</type>
        <desc>Promise if no callback passed</desc>
      </return>
      <signature>command(command, options, callback)</signature>
      <class>Admin</class>
      <desc>Execute a command</desc>
    </method>
    <method>
      <name>BulkWriteError</name>
      <parameters>
        <param>
          <optional>false</optional>
          <options/>
          <type>Error
|

string
|

object</type>
          <name>message</name>
          <desc>The error message</desc>
        </param>
        <param>
          <optional>false</optional>
          <options/>
          <type>BulkWriteResult</type>
          <name>result</name>
          <desc>The result of the bulk write operation</desc>
        </param>
      </parameters>
      <return>
        <type>BulkWriteError</type>
        <desc>BulkWriteError instance</desc>
      </return>
      <signature>new BulkWriteError(message, result)</signature>
      <class>BulkWriteError</class>
      <desc>Creates a new BulkWriteError</desc>
    </method>
    <method>
      <name>batchSize</name>
      <parameters>
        <param>
          <optional>false</optional>
          <options/>
          <type>number</type>
          <name>value</name>
          <desc>The batchSize for the cursor.</desc>
        </param>
      </parameters>
      <return>
        <type>AggregationCursor</type>
        <desc/>
</return>
      <signature>batchSize(value)</signature>
      <class>AggregationCursor</class>
      <desc>Set the batch size for the cursor.</desc>
    </method>
    <method>
      <name>listDatabases</name>
      <parameters>
        <param>
          <optional>true</optional>
          <options>
            <option>
              <default>false</default>
              <type>boolean</type>
              <name>nameOnly</name>
              <desc>Whether the command should return only db names, or names and size info.</desc>
            </option>
            <option>
              <default/>
              <type>ClientSession</type>
              <name>session</name>
              <desc>optional session to use for this operation</desc>
            </option>
          </options>
          <type>object</type>
          <name>options</name>
          <desc>Optional settings</desc>
        </param>
        <param>
          <optional>false</optional>
          <options/>
          <type>Admin~resultCallback</type>
          <name>callback</name>
          <desc>optional
The command result callback.</desc>
        </param>
      </parameters>
      <return>
        <type>Promise</type>
        <desc>Promise if no callback passed</desc>
      </return>
      <signature>listDatabases(options, callback)</signature>
      <class>Admin</class>
      <desc>List the available databases</desc>
    </method>
    <method>
      <name>ping</name>
      <parameters>
        <param>
          <optional>true</optional>
          <options>
            <option>
              <default/>
              <type>ClientSession</type>
              <name>session</name>
              <desc>optional session to use for this operation</desc>
            </option>
          </options>
          <type>Object</type>
          <name>options</name>
          <desc>Optional settings</desc>
        </param>
        <param>
          <optional>false</optional>
          <options/>
          <type>Admin~resultCallback</type>
          <name>callback</name>
          <desc>optional
The command result callback</desc>
        </param>
      </parameters>
      <return>
        <type>Promise</type>
        <desc>Promise if no callback passed</desc>
      </return>
      <signature>ping(options, callback)</signature>
      <class>Admin</class>
      <desc>Ping the MongoDB server and retrieve results</desc>
    </method>
    <method>
      <name>close</name>
      <parameters>
        <param>
          <optional>false</optional>
          <options/>
          <type>AggregationCursor~resultCallback</type>
          <name>callback</name>
          <desc>optional
The result callback.</desc>
        </param>
      </parameters>
      <return>
        <type>Promise</type>
        <desc>Promise if no callback passed</desc>
      </return>
      <signature>close(callback)</signature>
      <class>AggregationCursor</class>
      <desc>Close the cursor, sending a AggregationCursor command and emitting close.</desc>
    </method>
    <method>
      <name>each</name>
      <parameters>
        <param>
          <optional>false</optional>
          <options/>
          <type>AggregationCursor~resultCallback</type>
          <name>callback</name>
